### ISSUE TITLE
Pontuação se mantém após reinicio da cena

### ISSUE THREAD

**Issue by EnzoRobaina** [EnzoRobaina/Unity#2]
## Projeto da Nave 
No script de jogo a pontuação está definida assim, funciona, mas não reseta ao reiniciar a cena.
```c#
private static int pontos = 0;

	void Start(){
		jogo = GameObject.FindGameObjectWithTag ("GameController")
						 .GetComponent<Jogo> ();
		pontuacao = GameObject.FindGameObjectWithTag("Canvas").GetComponent<Text>();
	}
```
Defini assim, mas agora a pontuação não incrementa.
```c#
private static int pontos;

	void Start(){
		jogo = GameObject.FindGameObjectWithTag ("GameController")
						 .GetComponent<Jogo> ();
                pontos = 0;
		pontuacao = GameObject.FindGameObjectWithTag("Canvas").GetComponent<Text>();
	}
```

**Comment by EnzoRobaina** [comment]
@elissonmichael 🛸

**Comment by elissonmichael** [comment]
@EnzoRobaina, é interessante você tirar suas dúvidas lá na equipe (*team*) para outros colegas de classe poderem conferir. Acredito que postando a dúvida aqui a turma não recebe um e-mail. 

Minha contribuição para seu problema:

1. Se você usar `static` (atributo de classe) você precisa "zerar" a pontuação antes de reiniciar a cena (a informação persisti). 
2. Se você quiser alterar uma variável de classe dentro de um método, o ideal é que seja uma método de classe (método `static`), ou seja, você precisa deixar de usar uma variável de classe ou passar a usar um método de classe para altera-lá. 

Entendeu?

Bons estudos. Qualquer coisa, continua tirando dúvida lá na *Team*.
